name: Windows Build with GCC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Windows Server 2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW (GCC for Windows)
      run: |
        choco install mingw -y --no-progress
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Compile with GCC
      run: |
        g++ -o CGW_Load.exe CGW_Load_routine_table.cpp

    - name: Run the executable
      run: |
        .\CGW_Load.exe
