name: Windows MinGW Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up MSYS2 and MinGW
      run: |
        Invoke-WebRequest -Uri "https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-base-x86_64-latest.sfx.exe" -OutFile msys2.exe
        .\msys2.exe -y -oC:\msys64
        C:\msys64\usr\bin\bash -lc "pacman -Syu --noconfirm mingw-w64-x86_64-gcc"
        echo "C:\msys64\mingw64\bin" >> $env:GITHUB_PATH
        
    - name: Compile
      run: |
        g++ -o CGW_Load.exe CGW_Load_routine_table.cpp -std=c++11
